---
pool:
  name: 'Azure Pipelines'
  vmImage: ubuntu-latest

trigger:
  - main

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      feedsToUse: 'select'
      versioningScheme: 'off'  

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      feedsToUse: 'select'
      versioningScheme: 'off' 

  - task: NodeTool@0      
    inputs:
      versionSource: 'spec'     
      versionSpec: '16.x'

  - task: Npm@1
    inputs:
      command: install
      workingDir: MusicStore/ClientApp/ 

  - task: PublishTestResults@2       
    inputs:
      command: test
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop' 
      publishLocation: 'Container'     

          