---
pool:
  name: 'Azure Pipelines'
  vmImage: ubuntu-latest

trigger:
  - main

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      feedsToUse: 'select'
      versioningScheme: 'off'  

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      feedsToUse: 'select'
      versioningScheme: 'off' 

  - task: NodeTool@0      
    inputs:
      versionSource: 'spec'     
      versionSpec: '16.x'

  - task: Npm@1
    inputs:
      command: install
      workingDir: ./MusicStore/MusicStore/ClientApp/    
           